apiVersion: v1
kind: Secret
metadata:
  name: conversation-secret
  namespace: claro-coe-cxaas
type: Opaque 
data: 
  SPRING_DATASOURCE_PASSWORD: Q1NUTQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conversation-config
  namespace: claro-coe-cxaas
data:
  SPRING_APPLICATION_NAME: "conversation"
  SERVER_PORT: "8080"
  TZ: "America/Bogota"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_GENERATE_DDL: "none"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "oracle.jdbc.OracleDriver"
  SPRING_DATASOURCE_USERNAME: "CSTM"
  SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=lnxdbdevhw(PORT=1850))(CONNECT_DATA=(SERVER=dedicated)(SID=PDB_MASTERDEV)))"
  LOGGIN_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "info"
  LOGGIN_LEVEL_ORG_SPRINGFRAMEWORK_WS_CLIENT_MESSAGETRACING_SENT: "INFO"
  LOGGIN_LEVEL_ORG_SPRINGFRAMEWORK_WS_SERVER_MESSAGETRACING_SENT: "INFO"
  LOGGIN_LEVEL_ORG_SPRINGFRAMEWORK_WS_CLIENT_MESSAGETRACING_RECEIVED: "INFO"
  LOGGIN_LEVEL_ORG_SPRINGFRAMEWORK_WS_SERVER_MESSAGETRACING_RECEIVED: "INFO"
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: conversation
    legado: PDB_MASTERDEV
    proyecto: CXASS
    subproyecto: GENESYS
    tecnologia: SpringBoot-Maven
  name: organization
  namespace: claro-coe-cxaas
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: conversation
    deploymentconfig: conversation
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: 200m
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 10Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 120
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: conversation
        deploymentconfig: conversation
      name : conversation
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: conversation-config
            - secretRef:
                name: conversation-secret
          image: docker-registry.default.svc:5000/claro-coe-cxaas/conversation:latest
          imagePullPolicy: IfNotPresent
          name: conversation
          ports:
            - name : service-port
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: conversation
  name: conversation
  namespace: claro-coe-cxaas
spec:
  ports:
    - name : service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: conversation
    deploymentconfig: conversation
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: conversation
  name: conversation
  namespace: claro-coe-cxaas
spec:
  port:
    targetPort: service-port
  to:
    kind: Service
    name: conversation
    weight: 100
  wildcardPolicy: None